### ISSUE TITLE
Typescript path mapping is not recognized

### ISSUE THREAD

**Issue by danielkcz** [lwd-technology/react-app-rewire-typescript#9]
Basically, there needs to be the [tsconfig-paths-webpack-plugin](https://github.com/dividab/tsconfig-paths-webpack-plugin/) added to handle this gracefully. See [create-react-app-typescript](https://github.com/wmonk/create-react-app-typescript/blob/master/packages/react-scripts/config/webpack.config.dev.js#L127) using it.

**Comment by nathmack** [comment]
Also having this issue. Getting the following when starting my application: 
```
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'react-scripts/config/paths'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
```

**Comment by danielkcz** [comment]
I don't think anyone is going to maintain this considering there is a Babel TypeScript which is much easier to use with CRA.
